/* eslint-disable no-undef */
export type IconProps = JSX.IntrinsicAttributes & {
  as?: string | React.ReactSVGElement;
  width?: string | number;
  height?: string | number;
  className?: string;
} & React.SVGAttributes<SVGAElement> &
  React.ClassAttributes<HTMLDivElement> &
  React.HTMLAttributes<HTMLDivElement> & { children?: React.ReactNode };

export { default as AdjustmentsIcon } from './Adjustments';
export { default as ArchiveIcon } from './Archive';
export { default as ArrowDownIcon } from './ArrowDown';
export { default as ArrowLeftIcon } from './ArrowLeft';
export { default as ArrowRightIcon } from './ArrowRight';
export { default as ArrowSExpandIcon } from './ArrowSExpand';
export { default as ArrowUpIcon } from './ArrowUp';
export { default as AutoImportIcon } from './AutoImport';
export { default as BellIcon } from './Bell';
export { default as BookIcon } from './Book';
export { default as BranchIcon } from './Branch';
export { default as BriefcaseIcon } from './Briefcase';
export { default as CalendarIcon } from './Calendar';
export { default as CaretDownIcon } from './CaretDown';
export { default as CaretLeftIcon } from './CaretLeft';
export { default as CaretRightIcon } from './CaretRight';
export { default as CaretUpIcon } from './CaretUp';
export { default as ChartBarIcon } from './ChartBar';
export { default as ChartSquareBarIcon } from './ChartSquareBar';
export { default as CheckIcon } from './Check';
export { default as ChevronDownIcon } from './ChevronDown';
export { default as ChevronLeftIcon } from './ChevronLeft';
export { default as ChevronRightIcon } from './ChevronRight';
export { default as ChevronUpIcon } from './ChevronUp';
export { default as CircleCheckFilledIcon } from './CircleCheckFilled';
export { default as CircleCheckIcon } from './CircleCheck';
export { default as CircleErrorFilledIcon } from './CircleErrorFilled';
export { default as CircleErrorIcon } from './CircleError';
export { default as CircleHelpFilledIcon } from './CircleHelpFilled';
export { default as CircleHelpIcon } from './CircleHelp';
export { default as CircleInformationFilledIcon } from './CircleInformationFilled';
export { default as CircleInformationIcon } from './CircleInformation';
export { default as CircleWarningFilledIcon } from './CircleWarningFilled';
export { default as CircleWarningIcon } from './CircleWarning';
export { default as ClipboardIcon } from './Clipboard';
export { default as ClockIcon } from './Clock';
export { default as CodeIcon } from './Code';
export { default as CogIcon } from './Cog';
export { default as CommitIcon } from './Commit';
export { default as CompassIcon } from './Compass';
export { default as CreditCardIcon } from './CreditCard';
export { default as DatabaseIcon } from './Database';
export { default as DocumentTextIcon } from './DocumentText';
export { default as DotsHorizontalIcon } from './DotsHorizontal';
export { default as DownloadIcon } from './Download';
export { default as DuplicateIcon } from './Duplicate';
export { default as ExternalLinkIcon } from './ExternalLink';
export { default as EyeIcon } from './Eye';
export { default as EyeOffIcon } from './EyeOff';
export { default as FilterIcon } from './Filter';
export { default as FolderIcon } from './Folder';
export { default as GithubIcon } from './Github';
export { default as GoogleIcon } from './Google';
export { default as HomeIcon } from './Home';
export { default as LinkIcon } from './Link';
export { default as LockClosedIcon } from './LockClosed';
export { default as LogoutIcon } from './Logout';
export { default as MailIcon } from './Mail';
export { default as MinusIcon } from './Minus';
export { default as OfficeBuildingIcon } from './OfficeBuilding';
export { default as PencilIcon } from './Pencil';
export { default as Plus1Icon } from './Plus1';
export { default as PlusIcon } from './Plus';
export { default as PullRequestIcon } from './PullRequest';
export { default as RefreshIcon } from './Refresh';
export { default as RepositoryIcon } from './Repository';
export { default as SearchIcon } from './Search';
export { default as SelectorIcon } from './Selector';
export { default as ServerIcon } from './Server';
export { default as ShareIcon } from './Share';
export { default as SwitchVertical } from './SwitchVertical';
export { default as TableIcon } from './Table';
export { default as TerminalIcon } from './Terminal';
export { default as TrashIcon } from './Trash';
export { default as TrendDownIcon } from './TrendDown';
export { default as TrendUpIcon } from './TrendUp';
export { default as UploadIcon } from './Upload';
export { default as UserIcon } from './User';
export { default as UsersIcon } from './Users';
export { default as ViewGridIcon } from './ViewGrid';
export { default as WarningFilledIcon } from './WarningFilled';
export { default as WarningIcon } from './Warning';
export { default as XIcon } from './X';
